import { readFileSync } from 'fs'
import { describe, expect, it } from 'vitest'

const read = (path: string) => readFileSync(`packages/client/src/${path}`, 'utf8')

describe('Community restored configuration management', () => {
  it('moves Skills and Memory into the main-page top-left navigation', () => {
    const appSidebar = read('components/layout/AppSidebar.vue')
    const pageSidebar = read('components/layout/PageSidebarNav.vue')
    const app = read('App.vue')
    const chatView = read('views/hermes/ChatView.vue')
    const chatPanel = read('components/hermes/chat/ChatPanel.vue')
    const router = read('router/index.ts')
    expect(appSidebar).not.toContain('community-restored-hermes-config-links')
    expect(appSidebar.split(`:to="{ name: 'hermes.settings' }"`).length - 1).toBe(1)
    expect(appSidebar).toContain('t("sidebar.settings")')
    expect(appSidebar).not.toContain(`:to="{ name: 'hermes.skills' }"`)
    expect(appSidebar).not.toContain(`:to="{ name: 'hermes.memory' }"`)
    expect(pageSidebar).toContain('community-restored-main-nav-skills')
    expect(pageSidebar).toContain('community-restored-main-nav-memory')
    expect(pageSidebar).toContain("router.push({ name: 'hermes.mainSkills' })")
    expect(pageSidebar).toContain("router.push({ name: 'hermes.mainMemory' })")
    expect(pageSidebar).toContain("t('sidebar.skills')")
    expect(pageSidebar).toContain("t('sidebar.memory')")
    expect(pageSidebar).not.toContain("t('sidebar.apiRelay')")
    expect(app).toContain('\"hermes.mainSkills\"')
    expect(app).toContain('\"hermes.mainMemory\"')
    expect(chatView).toContain("route.name === 'hermes.models'")
    expect(chatView).toContain("route.name === 'hermes.mainSkills'")
    expect(chatView).toContain("route.name === 'hermes.mainMemory'")
    expect(chatPanel).toContain('contentMode?: \"chat\" | \"connections\" | \"agents\" | \"models\" | \"skills\" | \"memory\";')
    expect(chatPanel).toContain('SkillsPanel')
    expect(chatPanel).toContain('MemoryPanel')
    expect(chatPanel).toContain("contentMode === 'skills'")
    expect(chatPanel).toContain("contentMode === 'memory'")
    expect(router).toContain("path: '/hermes/main-skills'")
    expect(router).toContain("path: '/hermes/main-memory'")
    expect(router).toContain("component: () => import('@/views/hermes/ChatView.vue')")
    expect(router).toContain("component: () => import('@/views/hermes/SkillsView.vue')")
    expect(router).toContain("component: () => import('@/views/hermes/MemoryView.vue')")
  })

  it('uses upstream coding-agent settings for Claude settings.json and CLAUDE.md', () => {
    const manager = read('views/hermes/AgentManagerView.vue')
    const configView = read('views/hermes/CodingAgentConfigView.vue')
    expect(manager).not.toContain('community-restored-claude-config-button')
    expect(manager).not.toContain('ClaudeConfigEditor')
    expect(manager).toContain("name: 'codingAgent.config'")
    expect(manager).toContain("section: 'settings'")
    expect(configView).toContain("'claude-code': { preference: 'memory', configuration: 'settings' }")
    expect(configView).toContain('readCodingAgentConfigFile')
    expect(configView).toContain('writeCodingAgentConfigFile')
  })
})
